spring:
  application:
    name: user-service
    
  session:
    store-type: redis
#    redis:
#      flush-mode: on-save
#      namespace: spring:session

  redis:
    host: localhost
    port: 6379
    
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    
  jpa:
    show-sql: true  
  
server:
  port: 9090
  servlet:
    session:
      timeout: 600