pipeline {
    agent any

    stages {
		/*stage('Clean workspace') {
            steps {
			    deleteDir()
                sh 'ls -lah'
            }
        }*/
		stage('Checkout code') {
            steps {
			    checkout scm
            }
        }
        stage('Compile code') {
            steps {
                sh 'gradle clean'
            }
        }

    }
}